### PR TITLE
Code fixes for Live webpage

### PR DESCRIPTION
**Pull request by keeperkell**

### CODE REVIEW

**Comment by keeperkell** [comment]
If patient has insurance, tables are now displayed with a break between 
image

**Comment by keeperkell** [comment]
@carlkid1499 I have fixed the layout of the insurance tables and changed the syntax to the correct version for web deployment. I added in some test html and css changes for the welcome page that need to be pushed to live to check.

**Comment by carlkid1499** [comment]
Landing page looks great:
image


FLB Query works:
image

PID Query works:
image

FLE Query works:
image

All buttons work

**Review by carlkid1499 — APPROVED** [review]
All looks good!

**Pull request merged**
